// import AddIcon from "./add.svg"
// import AppsIcon from "./apps.svg"
// import ArrowDownwardIcon from "./arrow-downward.svg"
// import ArrowUpwardIcon from "./arrow-upward.svg"
// import AutorenewIcon from "./autorenew.svg"
// import CalendarIcon from "./calendar.svg"
// import CancleSolidIcon from "./cancel-solid.svg"
// import CheckedIcon from "./checkbox-checked.svg"
// import CheckDisabledIcon from "./checkbox-disabled.svg"
// import CheckIndeterminatedIcon from "./checkbox-indeterminated.svg"
// import UncheckedIcon from "./checkbox-unchecked.svg"
// import ChevronDownwardIcon from "./chevron-downward.svg"
// import ChevronLeftIcon from "./chevron-left.svg"
// import ChevronRightIcon from "./chevron-right.svg"
// import CloseIcon from "./close.svg"
// import DeleteIcon from "./delete.svg"
// import DocumentDefaultIcon from "./document-default.svg"
// import DocumentDownLoadIcon from "./document-download.svg"
// import DocumentUploadIcon from "./document-upload.svg"
// import DoneIcon from "./done.svg"
// import EletronicIcon from "./eletronic.svg"
// import EllipseIcon from "./ellipse.svg"
// import EmailIcon from "./email.svg"
// import ErrorIcon from "./error.svg"
// import FilterIcon from "./filter.svg"
// import FormatListNumberedIcon from "./format-list-numbered.svg"
// import FullscreenExitIcon from "./fullscreen-exit.svg"
// import FullscreenFullIcon from "./fullscreen-full.svg"
// import GridIcon from "./grid.svg"
// import HelpSolidIcon from "./help-solid.svg"
// import HelpIcon from "./help.svg"
// import LocationOnIcon from "./location-on.svg"
// import MapIcon from "./map.svg"
// import MenuIcon from "./menu.svg"
// import RadioSelectedIcon from "./radio-selected.svg"
// import RadioUnselectedIcon from "./radio-unselected.svg"
// import RefreshIcon from "./refresh.svg"
// import SearchIcon from "./search.svg"
// import SettingsIcon from "./settings.svg"
// import SuperuserIcon from "./superuser.svg"
// import ToggleDarkOffIcon from "./toggle-dark-off.svg"
// import ToggleDarkOnIcon from "./toggle-dark-on.svg"
// import ToggleLightOffDisabledIcon from "./toggle-light-off-disabled.svg"
// import ToggleLightOffIcon from "./toggle-light-off.svg"
// import ToggleLightOnDisabledIcon from "./toggle-light-on-disabled.svg"
// import ToggleLightOnIcon from "./toggle-light-on.svg"
// import TuneIcon from "./tune.svg"
// import UserIcon from "./user.svg"
// import VisibilityOffIcon from "./visibility-off.svg"
// import VisibilityOnIcon from "./visibility-on.svg"
// import ZoomInIcon from "./zoom-in.svg"


export * as AddIcon from "./add.svg"
export * as AppsIcon from "./apps.svg"
export * as ArrowDownwardIcon from "./arrow-downward.svg"
export * as ArrowUpwardIcon from "./arrow-upward.svg"
export * as AutorenewIcon from "./autorenew.svg"
export * as CalendarIcon from "./calendar.svg"
export * as CancleSolidIcon from "./cancel-solid.svg"
export * as CheckedIcon from "./checkbox-checked.svg"
export * as CheckDisabledIcon from "./checkbox-disabled.svg"
export * as CheckIndeterminatedIcon from "./checkbox-indeterminated.svg"
export * as UncheckedIcon from "./checkbox-unchecked.svg"
export * as ChevronDownwardIcon from "./chevron-downward.svg"
export * as ChevronLeftIcon from "./chevron-left.svg"
export * as ChevronRightIcon from "./chevron-right.svg"
export * as CloseIcon from "./close.svg"
export * as DeleteIcon from "./delete.svg"
export * as DocumentDefaultIcon from "./document-default.svg"
export * as DocumentDownLoadIcon from "./document-download.svg"
export * as DocumentUploadIcon from "./document-upload.svg"
export * as DoneIcon from "./done.svg"
export * as EletronicIcon from "./eletronic.svg"
export * as EllipseIcon from "./ellipse.svg"
export * as EmailIcon from "./email.svg"
export * as ErrorIcon from "./error.svg"
export * as FilterIcon from "./filter.svg"
export * as FormatListNumberedIcon from "./format-list-numbered.svg"
export * as FullscreenExitIcon from "./fullscreen-exit.svg"
export * as FullscreenFullIcon from "./fullscreen-full.svg"
export * as GridIcon from "./grid.svg"
export * as HelpSolidIcon from "./help-solid.svg"
export * as HelpIcon from "./help.svg"
export * as LocationOnIcon from "./location-on.svg"
export * as MapIcon from "./map.svg"
export * as MenuIcon from "./menu.svg"
export * as RadioSelectedIcon from "./radio-selected.svg"
export * as RadioUnselectedIcon from "./radio-unselected.svg"
export * as RefreshIcon from "./refresh.svg"
export * as SearchIcon from "./search.svg"
export * as SettingsIcon from "./settings.svg"
export * as SuperuserIcon from "./superuser.svg"
export * as ToggleDarkOffIcon from "./toggle-dark-off.svg"
export * as ToggleDarkOnIcon from "./toggle-dark-on.svg"
export * as ToggleLightOffDisabledIcon from "./toggle-light-off-disabled.svg"
export * as ToggleLightOffIcon from "./toggle-light-off.svg"
export * as ToggleLightOnDisabledIcon from "./toggle-light-on-disabled.svg"
export * as ToggleLightOnIcon from "./toggle-light-on.svg"
export * as TuneIcon from "./tune.svg"
export * as UserIcon from "./user.svg"
export * as VisibilityOffIcon from "./visibility-off.svg"
export * as VisibilityOnIcon from "./visibility-on.svg"
export * as ZoomInIcon from "./zoom-in.svg"

